name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"] # Ensure your primary branch is named "main"
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Detect package manager # <<
        uses: pnpm/action-setup@v3 # <<
        with: # <<
          version: 10 # <<
          
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build webmapper
        run: pnpm build:lib && pnpm build:web
        env:
          VITE_BASE_PATH: /library.js.coffee.2nd/app/webmapper/

      - name: Build webmsr-read
        run: pnpm build:msr
        env:
          VITE_BASE_PATH: /library.js.coffee.2nd/app/webmsr-read/

      - name: Build webibutton-read
        run: pnpm build:ibutton
        env:
          VITE_BASE_PATH: /library.js.coffee.2nd/app/webibutton-read/

      - name: Merge dist folders
        run: |
          mkdir -p ./deploy/app/webmapper
          mkdir -p ./deploy/app/webmsr-read
          mkdir -p ./deploy/app/webibutton-read
          cp -r ./packages/app/webmapper/dist/. ./deploy/app/webmapper/
          cp -r ./packages/app/webmsr-read/dist/. ./deploy/app/webmsr-read/
          cp -r ./packages/app/webibutton-read/dist/. ./deploy/app/webibutton-read/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './deploy'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
